In [18]:
import pandas as pd
import statsmodels.api as sms
import numpy as np

In [19]:
internet = pd.read_csv('internetusage.csv')
internet.head(5)

,State,Year,internet_usage,bachelors_degree,GDPpcGrowth,unemployment,Population,FarmEmploy,Forest&FishEmploy,Mining Employ,...,White,Black,NativeAmeri,Asian,PacificIslander,Other,Hispanic,SalesTax,LandArea,PovertyRate
0,Alabama,2010,61.7,22.0,-0.29,3.8,4785401,50168,14919,12015,...,0.695,0.264,0.006,0.011,0.000,0.011,0.038,4.00,"50,644",17.2
1,Alaska,2010,83.4,26.6,-3.50,9.3,714146,755,12069,17816,...,0.674,0.035,0.146,0.055,0.011,0.009,0.057,0.00,"570,665",12.5
2,Arizona,2010,74.3,25.6,-2.46,8.0,6413158,26348,15652,17977,...,0.794,0.041,0.045,0.027,0.002,0.064,0.298,5.60,"113,595",18.8
3,Arkansas,2010,63.4,18.9,0.75,10.4,2921588,56100,13849,16789,...,0.784,0.159,0.006,0.011,0.002,0.021,0.063,6.00,"52,030",15.3
4,California,2010,75.6,29.9,-0.97,7.9,37338198,237455,213933,60398,...,0.624,0.060,0.008,0.131,0.004,0.131,0.377,7.25,"155,766",16.3

In [20]:
new_var = sms.add_constant(internet['bachelors_degree'])
new_var.head()

   const  bachelors_degree
0    1.0              22.0
1    1.0              26.6
2    1.0              25.6
3    1.0              18.9
4    1.0              29.9

In [21]:
model=sms.OLS(internet['internet_usage'],sms.add_constant(internet['bachelors_degree'])).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:         internet_usage   R-squared:                       0.354
Model:                            OLS   Adj. R-squared:                  0.341
Method:                 Least Squares   F-statistic:                     26.89
Date:                Fri, 07 Oct 2022   Prob (F-statistic):           4.09e-06
Time:                        17:36:40   Log-Likelihood:                -154.61
No. Observations:                  51   AIC:                             313.2
Df Residuals:                      49   BIC:                             317.1
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               55.1103      3.665     15.037      0.000      47.745      62.475
bachelors_degree     0.6755      0.130      5.185      0.000       0.414       0.937
==============================================================================
Omnibus:                        3.456   Durbin-Watson:                   2.111
Prob(Omnibus):                  0.178   Jarque-Bera (JB):                2.474
Skew:                          -0.498   Prob(JB):                        0.290
Kurtosis:                       3.413   Cond. No.                         144.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
bach=float(int(10))

In [23]:
prediction=model.predict(pd.DataFrame({'intercept': 1,'bach':[bach]}))

In [24]:
print(prediction)

0    61.865155
dtype: float64